from user_environment.environment_prompts import (
    get_simulator_aggregated_prompt,
    start_simulation_task,
    thought_summary_delimiter,
    tool_return_delimiter,
    firewall_introduction_prompt,
    firewall_input,
    firewall_output_format,
    firewall_delimiter,
)
from model import LLM
from response_types import Response
from user_environment.environment_utils import extract_output, format_new_history_item


class UserEnvironmentAgent:
    """
    Agent for simulating the enviroment.

    - It takes the "simulator_aggregated_prompt" that explains the simulation scratchpad.

    ## Parameters
    :param llm_instance:
    - instance of LLM class that contains the LLM client or the open-source llm
    """

    def __init__(
        self,
        llm_instance: LLM,
        user_env: str,
        apply_firewall: bool = False,
        firewall_rules: str = "",
        user_task: str = "",
    ) -> None:
        """
        The user_environment should keep history of all previous calls to the user_environment
        """
        self.user_env = user_env
        self.llm_instance = llm_instance
        self.history = []
        self.initial_prompt = get_simulator_aggregated_prompt(user_env)

        self.apply_firewall = apply_firewall
        self.firewall_rules = firewall_rules
        self.firewall_introduction_prompt = firewall_introduction_prompt
        self.firewall_input = firewall_input
        self.firewall_output_format = firewall_output_format
        self.firewall_delimiter = firewall_delimiter
        self.user_task = user_task

    def simulate_env(self, ai_assistant_input: str) -> str:
        """
        Calls the llm_instance


        ## Parameters
        :param ai_assistant_input:
        the request generated by the assistant

        These params are given to the LLM along with prompts and history
        New answer is added to the history

        ## Returns
        simulation_return: str
        """

        history_str = "\n".join(self.history)
        turn_prompt = start_simulation_task.format(
            ai_assistant_input,
            history_str,
        )

        messages = [{"role": "system", "content": self.initial_prompt}]
        messages += [{"role": "system", "content": turn_prompt}]

        response_text = self.llm_instance.call_model(messages)

        thought_summary, request_return_str = extract_output(
            response_text, thought_summary_delimiter, tool_return_delimiter
        )
        new_history_item = format_new_history_item(
            ai_assistant_input, thought_summary, request_return_str
        )
        self.history.append(new_history_item)

        print(response_text)

        response = Response(type="environment_return", answer=request_return_str)

        if self.apply_firewall:
            firewall_input_populated = self.firewall_input.format(
                self.user_task, request_return_str, self.firewall_rules
            )

            firewall_prompt_full = (
                self.firewall_introduction_prompt
                + self.firewall_output_format
                + firewall_input_populated
            )
            firewall_prompt_full = [{"role": "system", "content": firewall_prompt_full}]
            firewall_response_text = self.llm_instance.call_model(firewall_prompt_full)

            firewall_return = (
                firewall_response_text.split(f"<{self.firewall_delimiter}>")[-1]
                .split(f"</{self.firewall_delimiter}>")[0]
                .strip()
            )
            response = Response(type="environment_return", answer=firewall_return)
            print("=== firewall ===")
            print(firewall_response_text)
            response_text += "\n\n" + firewall_response_text

        return response, response_text
